#!/bin/sh

# NOTE: this will currently only work on PPC

echo "Compiling the tester (and suppressing output)..."

g++ -o counter_tester counter_tester.c \
    -O2 -g -Wall \
    -DPRECISE_COUNTER -DTHUNKTESTER_TESTING -DOVM_PPC\
    -I. -I../common/include >& counter_test_compile_log || {
    echo "Failed to compile the tester:"
    cat counter_test_compile_log
    exit 1
}

echo "Running the tester:"

./counter_tester || {
    echo "TEST FAILED!!!"
    exit 1
}



