/* C file for payload */
/* generated by CFileGenerator.java in fivmc */
/* based on a LinkableSet with 128 linkables */
/* DO NOT EDIT DIRECTLY. */
#include <fivmr.h>
extern fivmr_Payload myhello_payload;
extern fivmr_Configuration myhello_config;
int64_t myhello_staticPrimFields[15];
fivmr_Object myhello_staticRefFields[108];
bool myhello_postThreadInitCback(fivmr_ThreadState *ts);
extern uintptr_t myhello_typeList[];
extern uintptr_t myhello_debugTable[];
extern uintptr_t myhello_stringTable[];
extern uintptr_t myhello_stringDataArray[];
extern uintptr_t myhello_classTable[];
extern fivmr_TypeData myhello_TypeData_Object_Hn3xU1ztLt86sM2N2WczH;
extern fivmr_TypeData myhello_TypeData_Class_IXNf0Nv01Zgfn7HgfEz413;
extern fivmr_TypeData myhello_TypeData_charArr_l3vFjwWeWLchNa4tr5HoK5;
extern fivmr_TypeData myhello_TypeData_vm_FCPtr_RXJlkedCSLtbjp4C2SYZW2;
extern fivmr_TypeData myhello_TypeData_void_au552JrSiVdXJTpoUumvq7;
extern fivmr_TypeData myhello_TypeData_booleanArr_gfzXZt9jGBwenAc28FEfS6;
extern fivmr_TypeData myhello_TypeData_longArr_IyYJgAzIvmrHWyFYSA0Nh5;
extern fivmr_TypeData myhello_TypeData_ObjectArr_Co3tdKymvNevWxnOinO652;
extern fivmr_TypeData myhello_TypeData_vm_FCPtrArr_0jAH6IfIHGlY2R2kAFpWf7;
extern fivmr_TypeData myhello_TypeData_long_ODGjCjLuSmdgk1yysabXl;
extern fivmr_TypeData myhello_TypeData_doubleArr_mjlqzFmth2EYGUJjMUzYX3;
extern fivmr_TypeData myhello_TypeData_char_GiXZWB9j4vBLRwx6WJyV86;
extern fivmr_TypeData myhello_TypeData_ClassArr_ZWels0iyzfCExJW1dfVMi6;
extern fivmr_TypeData myhello_TypeData_StringArr_Vb5Pt721nn40XyecOXIEG2;
extern fivmr_TypeData myhello_TypeData_byte_p0EiuVgIFBYQneSwHkWxN2;
extern fivmr_TypeData myhello_TypeData_String_cYEch6yLEtfhzvdGMDrzE5;
extern fivmr_TypeData myhello_TypeData_byteArr_nhLAxLkni0PhWM81bwqQW7;
extern fivmr_TypeData myhello_TypeData_short_31w3AaWO7w89oLerGEZ9h3;
extern fivmr_TypeData myhello_TypeData_double_9qhcjlYcEbW7W8Wvd29o68;
extern fivmr_TypeData myhello_TypeData_top_bkcp4oGc4D8yEEH7nlTJj6;
extern fivmr_TypeData myhello_TypeData_float_jYAb064TTl5ULSaM45eom3;
extern fivmr_TypeData myhello_TypeData_int_gv1gSVUGP0dW3cdLM7LmE8;
extern fivmr_TypeData myhello_TypeData_intArr_wA4JCC2DA3AFo22aSDOZ76;
extern fivmr_TypeData myhello_TypeData_floatArr_5YlNatn3OVHrdzH9hfwKk5;
extern fivmr_TypeData myhello_TypeData_pointerArr_mPM8X1CMEIVbdR2ahlrD34;
extern fivmr_TypeData myhello_TypeData_pointer_sEgXFRMZ4QGvR8UkdPirt7;
extern fivmr_TypeData myhello_TypeData_boolean_sY8z6fx1V8ILNqgtWTEA35;
extern fivmr_TypeData myhello_TypeData_shortArr_O9QqSxVPUYeTdeZkUTYxS2;
void myhello_fivmRuntime_notifyInitialized(uintptr_t arg0);
void myhello_returnBuffer(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getCString(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getCStringFull(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_VMThread_create(uintptr_t arg0,int32_t arg1,int8_t arg2);
void myhello_VMThread_setThreadState(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
uintptr_t myhello_VMThread_getThreadState(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_fromCStringInHeap(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_fromCStringFullInHeap(uintptr_t arg0,uintptr_t arg1);
void myhello_fivmRuntime_boot(uintptr_t arg0);
void myhello_VMThread_starting(uintptr_t arg0,uintptr_t arg1);
void myhello_throwNullPointerRTE(uintptr_t arg0);
void myhello_throwNullPointerRTE_inJava(uintptr_t arg0);
void myhello_throwArrayBoundsRTE_inJava(uintptr_t arg0);
void myhello_throwArrayStoreRTE_inJava(uintptr_t arg0);
void myhello_throwNegativeSizeRTE_inJava(uintptr_t arg0);
void myhello_throwClassCastRTE_inJava(uintptr_t arg0);
void myhello_throwClassChangeRTE_inJava(uintptr_t arg0);
void myhello_throwNoClassDefFoundError_inJava(uintptr_t arg0);
void myhello_throwNoClassDefFoundError(uintptr_t arg0);
void myhello_throwAbstractMethodError_inJava(uintptr_t arg0);
void myhello_throwUnsatisfiedLinkErrorForLoad(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void myhello_throwExceptionInInitializerError_inJava(uintptr_t arg0,uintptr_t arg1);
void myhello_throwReflectiveException_inJava(uintptr_t arg0,uintptr_t arg1);
void myhello_throwOutOfMemoryError_inJava(uintptr_t arg0);
void myhello_throwIllegalMonitorStateException_inJava(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_fromUTF16Sequence(uintptr_t arg0,uintptr_t arg1,int32_t arg2);
int32_t myhello_stringLength(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_cstringLength(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getUTF16Sequence(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getBooleanElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getByteElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getCharElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getShortElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getIntElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getLongElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getFloatElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_getDoubleElements(uintptr_t arg0,uintptr_t arg1);
void myhello_VMThread_run(uintptr_t arg0,uintptr_t arg1);
void myhello_returnBooleanElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void myhello_returnByteElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
int8_t myhello_VMThread_setUncaughtException(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void myhello_returnCharElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void myhello_returnShortElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void myhello_returnIntElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void myhello_VMThread_die(uintptr_t arg0,uintptr_t arg1);
void myhello_returnLongElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void myhello_returnFloatElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
int32_t myhello_VMThread_getPriority(uintptr_t arg0,uintptr_t arg1);
void myhello_returnDoubleElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
int8_t myhello_VMThread_isDaemon(uintptr_t arg0,uintptr_t arg1);
void myhello_getBooleanRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
uintptr_t myhello_TypeData_fromClass(uintptr_t arg0,uintptr_t arg1);
void myhello_getByteRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_getCharRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
uintptr_t myhello_String_getArrayPointer(uintptr_t arg0,uintptr_t arg1);
void myhello_getShortRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
int32_t myhello_String_getOffset(uintptr_t arg0,uintptr_t arg1);
void myhello_getIntRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_getLongRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_getFloatRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_getDoubleRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_setBooleanRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_setByteRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_setCharRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_setShortRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_setIntRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_setLongRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_setFloatRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_setDoubleRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_throwInternalError(uintptr_t arg0,uintptr_t arg1);
void myhello_throwNoSuchFieldError(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void myhello_throwNoSuchMethodError(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void myhello_throwNoSuchMethodError_inJava(uintptr_t arg0,uintptr_t arg1);
void myhello_describeExceptionImpl(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_allocForNative(uintptr_t arg0,int32_t arg1,uintptr_t arg2);
uintptr_t myhello_allocArrayForNative(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int32_t arg3);
uintptr_t myhello_DirectByteBuffer_wrap(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,int32_t arg4);
void myhello_makeJNIFuncName(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int8_t arg4);
uintptr_t myhello_processArgs(uintptr_t arg0,int32_t arg1,uintptr_t arg2);
uintptr_t myhello_DirectByteBuffer_address(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_DirectByteBuffer_capacity(uintptr_t arg0,uintptr_t arg1);
void myhello_getStringRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_getStringUTFRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void myhello_runRunnable(uintptr_t arg0,uintptr_t arg1);
void myhello_MemoryArea_doRun(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void myhello_javaExit(uintptr_t arg0,int32_t arg1);
uintptr_t myhello_MemoryArea_getBSID(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_BackingStoreID_create(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_DumpStackCback_cback(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
fivmr_Payload myhello_payload = {
   "0.9.0-r7db800193f83+",
   {
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
   },
   &myhello_config,
   FIVMR_PL_IMMORTAL_ONESHOT,
   NULL,
   (int32_t)370,
   (int32_t)15,
   (int32_t)108,
   myhello_staticPrimFields,
   myhello_staticRefFields,
   (int32_t)6229,
   (int32_t)364,
   (fivmr_TypeData**)myhello_typeList,
   (fivmr_DebugRec*)myhello_debugTable,
   (uintptr_t*)myhello_stringTable,
   (uintptr_t*)myhello_stringDataArray,
   (uintptr_t*)myhello_classTable,
   (uintptr_t)(intptr_t)-4,
   (uintptr_t)(intptr_t)-4,
   "myhello",
   "com/fiji/fivm/SCJMain",
   NULL,
   myhello_postThreadInitCback
,  (fivmr_TypeData*)&myhello_TypeData_top_bkcp4oGc4D8yEEH7nlTJj6
,  (fivmr_TypeData*)&myhello_TypeData_void_au552JrSiVdXJTpoUumvq7
,  (fivmr_TypeData*)&myhello_TypeData_boolean_sY8z6fx1V8ILNqgtWTEA35
,  (fivmr_TypeData*)&myhello_TypeData_byte_p0EiuVgIFBYQneSwHkWxN2
,  (fivmr_TypeData*)&myhello_TypeData_char_GiXZWB9j4vBLRwx6WJyV86
,  (fivmr_TypeData*)&myhello_TypeData_short_31w3AaWO7w89oLerGEZ9h3
,  (fivmr_TypeData*)&myhello_TypeData_int_gv1gSVUGP0dW3cdLM7LmE8
,  (fivmr_TypeData*)&myhello_TypeData_long_ODGjCjLuSmdgk1yysabXl
,  (fivmr_TypeData*)&myhello_TypeData_float_jYAb064TTl5ULSaM45eom3
,  (fivmr_TypeData*)&myhello_TypeData_double_9qhcjlYcEbW7W8Wvd29o68
,  (fivmr_TypeData*)&myhello_TypeData_pointer_sEgXFRMZ4QGvR8UkdPirt7
,  (fivmr_TypeData*)&myhello_TypeData_vm_FCPtr_RXJlkedCSLtbjp4C2SYZW2
,  (fivmr_TypeData*)&myhello_TypeData_Object_Hn3xU1ztLt86sM2N2WczH
,  (fivmr_TypeData*)&myhello_TypeData_String_cYEch6yLEtfhzvdGMDrzE5
,  (fivmr_TypeData*)&myhello_TypeData_Class_IXNf0Nv01Zgfn7HgfEz413
,  NULL
,  NULL
,  NULL
,  (fivmr_TypeData*)&myhello_TypeData_booleanArr_gfzXZt9jGBwenAc28FEfS6
,  (fivmr_TypeData*)&myhello_TypeData_byteArr_nhLAxLkni0PhWM81bwqQW7
,  (fivmr_TypeData*)&myhello_TypeData_charArr_l3vFjwWeWLchNa4tr5HoK5
,  (fivmr_TypeData*)&myhello_TypeData_shortArr_O9QqSxVPUYeTdeZkUTYxS2
,  (fivmr_TypeData*)&myhello_TypeData_intArr_wA4JCC2DA3AFo22aSDOZ76
,  (fivmr_TypeData*)&myhello_TypeData_longArr_IyYJgAzIvmrHWyFYSA0Nh5
,  (fivmr_TypeData*)&myhello_TypeData_floatArr_5YlNatn3OVHrdzH9hfwKk5
,  (fivmr_TypeData*)&myhello_TypeData_doubleArr_mjlqzFmth2EYGUJjMUzYX3
,  (fivmr_TypeData*)&myhello_TypeData_pointerArr_mPM8X1CMEIVbdR2ahlrD34
,  (fivmr_TypeData*)&myhello_TypeData_vm_FCPtrArr_0jAH6IfIHGlY2R2kAFpWf7
,  (fivmr_TypeData*)&myhello_TypeData_ObjectArr_Co3tdKymvNevWxnOinO652
,  (fivmr_TypeData*)&myhello_TypeData_StringArr_Vb5Pt721nn40XyecOXIEG2
,  (fivmr_TypeData*)&myhello_TypeData_ClassArr_ZWels0iyzfCExJW1dfVMi6
,  myhello_TypeData_fromClass
,  myhello_fivmRuntime_boot
,  myhello_fivmRuntime_notifyInitialized
,  myhello_allocForNative
,  myhello_allocArrayForNative
,  myhello_throwInternalError
,  myhello_throwNoClassDefFoundError
,  myhello_throwNoClassDefFoundError_inJava
,  myhello_throwNullPointerRTE
,  myhello_throwNullPointerRTE_inJava
,  myhello_throwClassChangeRTE_inJava
,  myhello_throwArrayBoundsRTE_inJava
,  myhello_throwArrayStoreRTE_inJava
,  myhello_throwNegativeSizeRTE_inJava
,  myhello_throwAbstractMethodError_inJava
,  myhello_throwClassCastRTE_inJava
,  myhello_throwUnsatisfiedLinkErrorForLoad
,  myhello_throwNoSuchFieldError
,  myhello_throwNoSuchMethodError
,  myhello_throwNoSuchMethodError_inJava
,  myhello_throwExceptionInInitializerError_inJava
,  myhello_throwReflectiveException_inJava
,  myhello_throwIllegalMonitorStateException_inJava
,  myhello_throwOutOfMemoryError_inJava
,  myhello_describeExceptionImpl
,  myhello_fromCStringInHeap
,  myhello_fromCStringFullInHeap
,  myhello_fromUTF16Sequence
,  myhello_stringLength
,  myhello_cstringLength
,  myhello_getUTF16Sequence
,  myhello_getCString
,  myhello_getCStringFull
,  myhello_getStringRegion
,  myhello_getStringUTFRegion
,  myhello_String_getArrayPointer
,  myhello_String_getOffset
,  myhello_getBooleanElements
,  myhello_getByteElements
,  myhello_getCharElements
,  myhello_getShortElements
,  myhello_getIntElements
,  myhello_getLongElements
,  myhello_getFloatElements
,  myhello_getDoubleElements
,  myhello_returnBooleanElements
,  myhello_returnByteElements
,  myhello_returnCharElements
,  myhello_returnShortElements
,  myhello_returnIntElements
,  myhello_returnLongElements
,  myhello_returnFloatElements
,  myhello_returnDoubleElements
,  myhello_getBooleanRegion
,  myhello_getByteRegion
,  myhello_getCharRegion
,  myhello_getShortRegion
,  myhello_getIntRegion
,  myhello_getLongRegion
,  myhello_getFloatRegion
,  myhello_getDoubleRegion
,  myhello_setBooleanRegion
,  myhello_setByteRegion
,  myhello_setCharRegion
,  myhello_setShortRegion
,  myhello_setIntRegion
,  myhello_setLongRegion
,  myhello_setFloatRegion
,  myhello_setDoubleRegion
,  myhello_returnBuffer
,  myhello_DirectByteBuffer_wrap
,  myhello_DirectByteBuffer_address
,  myhello_DirectByteBuffer_capacity
,  myhello_VMThread_create
,  myhello_VMThread_setThreadState
,  myhello_VMThread_getThreadState
,  myhello_VMThread_starting
,  myhello_VMThread_run
,  myhello_VMThread_setUncaughtException
,  myhello_VMThread_die
,  myhello_VMThread_isDaemon
,  myhello_VMThread_getPriority
,  myhello_DumpStackCback_cback
,  myhello_makeJNIFuncName
,  myhello_runRunnable
,  myhello_MemoryArea_doRun
,  myhello_MemoryArea_getBSID
,  myhello_BackingStoreID_create
,  myhello_processArgs
,  myhello_javaExit
};
