/* C file for upcalls */
/* generated by CFileGenerator.java in fivmc */
/* based on a LinkableSet with 129 linkables */
/* DO NOT EDIT DIRECTLY. */
#include <fivmr.h>
void myhello_upcall_QCPf92QF0S0jZGO8QFFuK(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_QCPf92QF0S0jZGO8QFFuK(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int16_t myhello_upcall_C25jp525lXgGEPmXzX7yX(uintptr_t arg0,uintptr_t arg1);
int16_t myhello_upcall_C25jp525lXgGEPmXzX7yX(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_a5Zk9vPQxEjoQ7HcHqERf(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_a5Zk9vPQxEjoQ7HcHqERf(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_ioQSTIaCNchJpAB17nG4L(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_ioQSTIaCNchJpAB17nG4L(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_WhmGrIJglGKYZc9ZG3OkL6(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_WhmGrIJglGKYZc9ZG3OkL6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_RiDMl70zKfQNidwFfuv117(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_RiDMl70zKfQNidwFfuv117(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_OZQt3gbwDfmqg0PrA9CSr7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_OZQt3gbwDfmqg0PrA9CSr7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_FBM1ctgEalAeq7DdFvLBu7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_FBM1ctgEalAeq7DdFvLBu7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_PzRjdCVLYQGF5f7oP9tl43(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_PzRjdCVLYQGF5f7oP9tl43(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_HrIm6qP70fnirHg1iFuwW7(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_HrIm6qP70fnirHg1iFuwW7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_bTzvEU9YJ7ywNdrly1Msa5(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_bTzvEU9YJ7ywNdrly1Msa5(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int16_t myhello_upcall_u7PpTmKSMq3N88UyAYPpx3(uintptr_t arg0,uintptr_t arg1);
int16_t myhello_upcall_u7PpTmKSMq3N88UyAYPpx3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int32_t myhello_upcall_gL0Zc7iY5o2vr2OifRFXf4(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_upcall_gL0Zc7iY5o2vr2OifRFXf4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_Y0xWj0d7joaiUHBph1Tbz8(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_Y0xWj0d7joaiUHBph1Tbz8(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_bCoxZ9cDa8osG8f8wLlZi8(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_bCoxZ9cDa8osG8f8wLlZi8(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_yEDw5JiKTHCFCNXUBiY3a8(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_yEDw5JiKTHCFCNXUBiY3a8(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_DfZykm0sNfrmzK3eCKQkT6(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_DfZykm0sNfrmzK3eCKQkT6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_sDOvFGxhpyLVku4gmJK6g(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_sDOvFGxhpyLVku4gmJK6g(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_Vyeai8w8VjG57RjoovJnA4(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_Vyeai8w8VjG57RjoovJnA4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_N6sgcgtfEXNPz8B4dxaxG7(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_N6sgcgtfEXNPz8B4dxaxG7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int32_t myhello_upcall_j2BXkfrSEr1Yq2b6I6K2G(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_upcall_j2BXkfrSEr1Yq2b6I6K2G(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_9MTj6G1MzZIek833ArlFo3(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_9MTj6G1MzZIek833ArlFo3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_hEo9Epuivu9VS1sgH4b3h8(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_hEo9Epuivu9VS1sgH4b3h8(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_MftMtqWuIzb2QtDbuFCHb4(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_MftMtqWuIzb2QtDbuFCHb4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uint16_t myhello_upcall_8GulED1PxCdCGJG6VUeUJ3(uintptr_t arg0,uintptr_t arg1);
uint16_t myhello_upcall_8GulED1PxCdCGJG6VUeUJ3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_iekqEpCxt8kvlowQ4B5TJ3(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_iekqEpCxt8kvlowQ4B5TJ3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
float myhello_upcall_DqVkGcIf51XjXHAb8EIoj5(uintptr_t arg0,uintptr_t arg1);
float myhello_upcall_DqVkGcIf51XjXHAb8EIoj5(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
double myhello_upcall_nSrUdYFtNs2K68H5CTXHp3(uintptr_t arg0,uintptr_t arg1);
double myhello_upcall_nSrUdYFtNs2K68H5CTXHp3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
double myhello_upcall_97wT9Z6SSyXhObwKeEHvi6(uintptr_t arg0,uintptr_t arg1);
double myhello_upcall_97wT9Z6SSyXhObwKeEHvi6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
float myhello_upcall_8hzybitrA4MyrVRzTAw3p6(uintptr_t arg0,uintptr_t arg1);
float myhello_upcall_8hzybitrA4MyrVRzTAw3p6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_Ip7TMwrhfpiVEw2ouohrm(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_Ip7TMwrhfpiVEw2ouohrm(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_KyzHo0mGe3DBc3cd5nWgP7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_KyzHo0mGe3DBc3cd5nWgP7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_Vglkr7zH9ehchOKO5shB26(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_Vglkr7zH9ehchOKO5shB26(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_4iq8C9YnZmhvjgotgM7yr7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_4iq8C9YnZmhvjgotgM7yr7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_hGIsPTNlkvtLuVcNX6TqV7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_hGIsPTNlkvtLuVcNX6TqV7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_MExKdcCfYtjxEH1UuXnUL6(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_MExKdcCfYtjxEH1UuXnUL6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int32_t myhello_upcall_TBJ0GA5YHpU5eFMrGn4Nl2(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_upcall_TBJ0GA5YHpU5eFMrGn4Nl2(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int64_t myhello_upcall_2KFBSwwHBNpiI6EKYb5Hx7(uintptr_t arg0,uintptr_t arg1);
int64_t myhello_upcall_2KFBSwwHBNpiI6EKYb5Hx7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_q3Yd6lhW7SOB2uaD8UzY46(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_q3Yd6lhW7SOB2uaD8UzY46(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_qesWY6py0rj8w5K0v9gmH7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_qesWY6py0rj8w5K0v9gmH7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_DlXhFTsI4rbbYRPk6ci568(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_DlXhFTsI4rbbYRPk6ci568(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_xtplxCUNH9hoUHibjyHDr(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_xtplxCUNH9hoUHibjyHDr(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_sG2fKZUmVJNOBq6rYsL1y5(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_sG2fKZUmVJNOBq6rYsL1y5(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_lHRYHiyYMGgx0d1XdShF85(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_lHRYHiyYMGgx0d1XdShF85(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uint16_t myhello_upcall_R80Tm0zu6lPlrPpzU22V87(uintptr_t arg0,uintptr_t arg1);
uint16_t myhello_upcall_R80Tm0zu6lPlrPpzU22V87(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int64_t myhello_upcall_aEzr23zCPKfe1fXelr305(uintptr_t arg0,uintptr_t arg1);
int64_t myhello_upcall_aEzr23zCPKfe1fXelr305(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_dWOanDboJh1KmRiOCPpbK4(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_dWOanDboJh1KmRiOCPpbK4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_ADQhs6XF4QbsWN6KmxRZA2(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_ADQhs6XF4QbsWN6KmxRZA2(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_H0L1TqhiKEufSuBF7inav2(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_H0L1TqhiKEufSuBF7inav2(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_cI2OKU5UNUJDsnfKK5byS7(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_cI2OKU5UNUJDsnfKK5byS7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_NfLrRofZrGfFIqokieLHF7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_NfLrRofZrGfFIqokieLHF7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_RQmroVTzHhJaIQXFl9bh73(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_RQmroVTzHhJaIQXFl9bh73(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_ZhUhzaNNnNtGhcgK3jQ2p(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_ZhUhzaNNnNtGhcgK3jQ2p(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_ylb36BoSuhu2Hxgfjy2264(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_ylb36BoSuhu2Hxgfjy2264(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_gLvGw6pnk7adUAtHTIqFG2(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_gLvGw6pnk7adUAtHTIqFG2(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_wXdCkTGvqKGdxXucvDMDn(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_wXdCkTGvqKGdxXucvDMDn(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_ih0WoD1E2yxw08VLYQszy4(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_ih0WoD1E2yxw08VLYQszy4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_jf37Q2ElCaEBXuF100HaE7(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_jf37Q2ElCaEBXuF100HaE7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_ENSTGmF5FyL7l7dG8tSJ36(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_ENSTGmF5FyL7l7dG8tSJ36(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_KoNqjiiEQiuDKzYvBmfqA2(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_KoNqjiiEQiuDKzYvBmfqA2(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_OGhofjSUaJ2BZL8IdUtPF4(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_OGhofjSUaJ2BZL8IdUtPF4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_5SI0TRwmKS0EpfjLnWA5l8(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_5SI0TRwmKS0EpfjLnWA5l8(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_8KIEOOq5HFzOxJBvzzmms7(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_8KIEOOq5HFzOxJBvzzmms7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_eQYtyNCiIOnnAkOQLrBlY3(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_eQYtyNCiIOnnAkOQLrBlY3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_SUaRBbPI4TN9WTN2pNfBJ6(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_SUaRBbPI4TN9WTN2pNfBJ6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_nATwijWNDNmeQdUHtHVQV6(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_nATwijWNDNmeQdUHtHVQV6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_GGKHxiizNJlZqsc2e0BZ34(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_GGKHxiizNJlZqsc2e0BZ34(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_GrqdMAo5WADB2zdfFvqPW6(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_GrqdMAo5WADB2zdfFvqPW6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_HjgmkKI1RSaa4V5vemIas2(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_HjgmkKI1RSaa4V5vemIas2(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_gZ8rq5ucxynjsZlmAxEbu4(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_gZ8rq5ucxynjsZlmAxEbu4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int32_t myhello_upcall_xLfh0pQ4Zn9FkisFVa89A3(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_upcall_xLfh0pQ4Zn9FkisFVa89A3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_RhLfzuwC0JZAex2OaO7tL5(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_RhLfzuwC0JZAex2OaO7tL5(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_x4gf55Jz1AtMj6dBsceBw7(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_x4gf55Jz1AtMj6dBsceBw7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_SdeQzO4ZvTw1ksOmCLUew5(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_SdeQzO4ZvTw1ksOmCLUew5(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_OreI6NwjbDwF7L9hlVwOO(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_OreI6NwjbDwF7L9hlVwOO(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uint16_t myhello_upcall_6uDZ153UAuFFuxMyyJHUn7(uintptr_t arg0,uintptr_t arg1);
uint16_t myhello_upcall_6uDZ153UAuFFuxMyyJHUn7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_9wChVhfqNWnbbDskm1sR76(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_9wChVhfqNWnbbDskm1sR76(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_Ld9SvU4svrhpYNHWrxPCX4(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_Ld9SvU4svrhpYNHWrxPCX4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_nm1FwXESGHKMal5Lv9qvM(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_nm1FwXESGHKMal5Lv9qvM(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_FLBEHf56plJZsQaRLJ9B54(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_FLBEHf56plJZsQaRLJ9B54(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_UXa64oZrGrn6zyPhFFaV0(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_UXa64oZrGrn6zyPhFFaV0(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_ZFj5I46MFlvl8sVw3vaJs(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_ZFj5I46MFlvl8sVw3vaJs(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_6wFNMG8WooFRkyJs5YdMF5(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_6wFNMG8WooFRkyJs5YdMF5(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_psMber4py3FEOX8xCLN98(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_psMber4py3FEOX8xCLN98(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_4YbAUQ72hT6VHB9NHs69c7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_4YbAUQ72hT6VHB9NHs69c7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_wINsCfhllTCYpYynA9r0l4(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_wINsCfhllTCYpYynA9r0l4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_s5odBoQEG0baBSZvmYZwQ8(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_s5odBoQEG0baBSZvmYZwQ8(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_NxpQ5YtbvqOcbfmJNJxBl8(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_NxpQ5YtbvqOcbfmJNJxBl8(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_ZWD29W9sR3Q96cHPwjk8h4(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_ZWD29W9sR3Q96cHPwjk8h4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_kH6PPN83ygfntLHQVizqC(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_kH6PPN83ygfntLHQVizqC(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_y3kS1qVfG9MyWvFGfHW3Z4(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_y3kS1qVfG9MyWvFGfHW3Z4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_ezccmrAkruGgEkrhl8mpE8(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_ezccmrAkruGgEkrhl8mpE8(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_I6dkRK8TStZGxESt2WzJq4(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_I6dkRK8TStZGxESt2WzJq4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int64_t myhello_upcall_o2qQG8OzJbUTw3SsZqMR23(uintptr_t arg0,uintptr_t arg1);
int64_t myhello_upcall_o2qQG8OzJbUTw3SsZqMR23(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_TbiobxppawChoS8YYO6J7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_TbiobxppawChoS8YYO6J7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_fm0lss3LkeofuMMwa0mRD3(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_fm0lss3LkeofuMMwa0mRD3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_yc1DbLn7z8aAJz4OWFTUC7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_yc1DbLn7z8aAJz4OWFTUC7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int32_t myhello_upcall_rYd9z2PPbe1lHPQI1LRZj7(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_upcall_rYd9z2PPbe1lHPQI1LRZj7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_PY1AHtP1YMQgCcBNbweW07(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_PY1AHtP1YMQgCcBNbweW07(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_3ixwtIxLzRZUDsLpWdJen2(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_3ixwtIxLzRZUDsLpWdJen2(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_LWyYqU3x72xiHwuQsavdY2(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_LWyYqU3x72xiHwuQsavdY2(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int64_t myhello_upcall_WhOlXIb2zpd9wco4I7Eli3(uintptr_t arg0,uintptr_t arg1);
int64_t myhello_upcall_WhOlXIb2zpd9wco4I7Eli3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_WHujB3wSDm2GuqwOctpLv7(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_WHujB3wSDm2GuqwOctpLv7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int32_t myhello_upcall_14g9OHkLNmJeAU9mfGCEx7(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_upcall_14g9OHkLNmJeAU9mfGCEx7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_11sr2zMf8hDcUmQc4E31A(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_11sr2zMf8hDcUmQc4E31A(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_Q2BVUjXGFcCUR5oy8x3nc6(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_Q2BVUjXGFcCUR5oy8x3nc6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_XfBho7AfVJ6RXc92u5gBN6(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_XfBho7AfVJ6RXc92u5gBN6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_zEh95pYK9loSV15m2YAo25(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_zEh95pYK9loSV15m2YAo25(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_Yep7WKCoQMq7TWX44UuTD5(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_Yep7WKCoQMq7TWX44UuTD5(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_wsci3sC4LgjAbTUPEjLJb(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_wsci3sC4LgjAbTUPEjLJb(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_PRvKNCn8iqyO1ws29tvvH4(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_PRvKNCn8iqyO1ws29tvvH4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int32_t myhello_upcall_F2bTMdNJ2c555by8BWRd33(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_upcall_F2bTMdNJ2c555by8BWRd33(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_lOQ0tMMdVOAoOBpJdEetr6(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_lOQ0tMMdVOAoOBpJdEetr6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_qNLOhSn95RzX5lXyOeEFz7(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_qNLOhSn95RzX5lXyOeEFz7(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_GRUwxlsmMVYTgwluJUVhy6(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_GRUwxlsmMVYTgwluJUVhy6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_ZPxKgPFIW6PvV8j56bZjB6(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_ZPxKgPFIW6PvV8j56bZjB6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_ACjFZVKF6lEhU76iQRZYF4(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_ACjFZVKF6lEhU76iQRZYF4(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int32_t myhello_upcall_aGQz3o2R3jbguIwq2tb0S6(uintptr_t arg0,uintptr_t arg1);
int32_t myhello_upcall_aGQz3o2R3jbguIwq2tb0S6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_diyWWwdzHBj594YNWILF85(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_diyWWwdzHBj594YNWILF85(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_PnLeTu8HxtNoUQ3U93aQG5(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_PnLeTu8HxtNoUQ3U93aQG5(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_PiK8NTbLRMcJKb9Oolb4d3(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_PiK8NTbLRMcJKb9Oolb4d3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_db1YjOISfp2Hhc9965gF(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_db1YjOISfp2Hhc9965gF(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_h2BMU5XjiwqAqdKfHQCH9(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_h2BMU5XjiwqAqdKfHQCH9(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_RNTFqwMK8u4boMD9Rabdy8(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_RNTFqwMK8u4boMD9Rabdy8(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_fyTphXgtNAhOA5Q2LFpih(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_fyTphXgtNAhOA5Q2LFpih(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int8_t myhello_upcall_dIY2zU01pkPn8JFt4DhAd6(uintptr_t arg0,uintptr_t arg1);
int8_t myhello_upcall_dIY2zU01pkPn8JFt4DhAd6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
uintptr_t myhello_upcall_ZscDmd95HpXPeNPoMGERa3(uintptr_t arg0,uintptr_t arg1);
uintptr_t myhello_upcall_ZscDmd95HpXPeNPoMGERa3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
int64_t myhello_upcall_7tqbcL37gA1nG2595jGYC3(uintptr_t arg0,uintptr_t arg1);
int64_t myhello_upcall_7tqbcL37gA1nG2595jGYC3(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_nA9IjQoo2lPsbH6FUpLBk6(uintptr_t arg0,uintptr_t arg1);
void myhello_upcall_nA9IjQoo2lPsbH6FUpLBk6(uintptr_t arg0,uintptr_t arg1) __attribute__((noinline));
void myhello_upcall_QCPf92QF0S0jZGO8QFFuK(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1) = (void (*)(uintptr_t arg0,uintptr_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P);
}
int16_t myhello_upcall_C25jp525lXgGEPmXzX7yX(uintptr_t arg0,uintptr_t arg1) {
   int16_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (int16_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I);
}
void myhello_upcall_a5Zk9vPQxEjoQ7HcHqERf(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int8_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int8_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].Z);
}
uintptr_t myhello_upcall_ioQSTIaCNchJpAB17nG4L(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P);
}
uintptr_t myhello_upcall_WhmGrIJglGKYZc9ZG3OkL6(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,int8_t arg2) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,int8_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].Z);
}
void myhello_upcall_RiDMl70zKfQNidwFfuv117(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].I, args[4].P);
}
void myhello_upcall_OZQt3gbwDfmqg0PrA9CSr7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0) = (void (*)(uintptr_t arg0))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P);
}
void myhello_upcall_FBM1ctgEalAeq7DdFvLBu7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int8_t arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int8_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].Z, args[4].I);
}
uintptr_t myhello_upcall_PzRjdCVLYQGF5f7oP9tl43(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3,uintptr_t arg4,int32_t arg5,uintptr_t arg6) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3,uintptr_t arg4,int32_t arg5,uintptr_t arg6))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].I, args[3].P, args[4].P, args[5].I, args[6].P);
}
uintptr_t myhello_upcall_HrIm6qP70fnirHg1iFuwW7(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I);
}
void myhello_upcall_bTzvEU9YJ7ywNdrly1Msa5(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].I);
}
int16_t myhello_upcall_u7PpTmKSMq3N88UyAYPpx3(uintptr_t arg0,uintptr_t arg1) {
   int16_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (int16_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I);
}
int32_t myhello_upcall_gL0Zc7iY5o2vr2OifRFXf4(uintptr_t arg0,uintptr_t arg1) {
   int32_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (int32_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I);
}
int8_t myhello_upcall_Y0xWj0d7joaiUHBph1Tbz8(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I);
}
void myhello_upcall_bCoxZ9cDa8osG8f8wLlZi8(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].P, args[4].I);
}
void myhello_upcall_yEDw5JiKTHCFCNXUBiY3a8(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].I);
}
void myhello_upcall_DfZykm0sNfrmzK3eCKQkT6(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int8_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int8_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].B);
}
uintptr_t myhello_upcall_sDOvFGxhpyLVku4gmJK6g(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I);
}
void myhello_upcall_Vyeai8w8VjG57RjoovJnA4(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,float arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,float arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].F, args[4].I);
}
uintptr_t myhello_upcall_N6sgcgtfEXNPz8B4dxaxG7(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,uintptr_t arg2) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,uintptr_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].P);
}
int32_t myhello_upcall_j2BXkfrSEr1Yq2b6I6K2G(uintptr_t arg0,uintptr_t arg1) {
   int32_t (*func)(uintptr_t arg0,uintptr_t arg1) = (int32_t (*)(uintptr_t arg0,uintptr_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P);
}
void myhello_upcall_9MTj6G1MzZIek833ArlFo3(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int64_t arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int64_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].J, args[4].I);
}
void myhello_upcall_hEo9Epuivu9VS1sgH4b3h8(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int16_t arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int16_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].S, args[4].I);
}
uintptr_t myhello_upcall_MftMtqWuIzb2QtDbuFCHb4(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3,uintptr_t arg4,uintptr_t arg5,uintptr_t arg6) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3,uintptr_t arg4,uintptr_t arg5,uintptr_t arg6))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].I, args[3].P, args[4].P, args[5].P, args[6].P);
}
uint16_t myhello_upcall_8GulED1PxCdCGJG6VUeUJ3(uintptr_t arg0,uintptr_t arg1) {
   uint16_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (uint16_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I);
}
int8_t myhello_upcall_iekqEpCxt8kvlowQ4B5TJ3(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I);
}
float myhello_upcall_DqVkGcIf51XjXHAb8EIoj5(uintptr_t arg0,uintptr_t arg1) {
   float (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (float (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I);
}
double myhello_upcall_nSrUdYFtNs2K68H5CTXHp3(uintptr_t arg0,uintptr_t arg1) {
   double (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (double (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I);
}
double myhello_upcall_97wT9Z6SSyXhObwKeEHvi6(uintptr_t arg0,uintptr_t arg1) {
   double (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (double (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I);
}
float myhello_upcall_8hzybitrA4MyrVRzTAw3p6(uintptr_t arg0,uintptr_t arg1) {
   float (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (float (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I);
}
void myhello_upcall_Ip7TMwrhfpiVEw2ouohrm(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].P);
}
void myhello_upcall_KyzHo0mGe3DBc3cd5nWgP7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P);
}
int8_t myhello_upcall_Vglkr7zH9ehchOKO5shB26(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I);
}
void myhello_upcall_4iq8C9YnZmhvjgotgM7yr7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int8_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int8_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].P, args[4].Z);
}
void myhello_upcall_hGIsPTNlkvtLuVcNX6TqV7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int8_t arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int8_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].B, args[4].I);
}
void myhello_upcall_MExKdcCfYtjxEH1UuXnUL6(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,double arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,double arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].D, args[4].I);
}
int32_t myhello_upcall_TBJ0GA5YHpU5eFMrGn4Nl2(uintptr_t arg0,uintptr_t arg1) {
   int32_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (int32_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I);
}
int64_t myhello_upcall_2KFBSwwHBNpiI6EKYb5Hx7(uintptr_t arg0,uintptr_t arg1) {
   int64_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (int64_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I);
}
uintptr_t myhello_upcall_q3Yd6lhW7SOB2uaD8UzY46(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,int32_t arg4) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I, args[3].I, args[4].I);
}
void myhello_upcall_qesWY6py0rj8w5K0v9gmH7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int64_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int64_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].J);
}
void myhello_upcall_DlXhFTsI4rbbYRPk6ci568(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int16_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int16_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].S);
}
void myhello_upcall_xtplxCUNH9hoUHibjyHDr(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,float arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,float arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].F);
}
void myhello_upcall_sG2fKZUmVJNOBq6rYsL1y5(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].I, args[4].I);
}
void myhello_upcall_lHRYHiyYMGgx0d1XdShF85(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4,int32_t arg5,uintptr_t arg6) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4,int32_t arg5,uintptr_t arg6))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].P, args[4].I, args[5].I, args[6].P);
}
uint16_t myhello_upcall_R80Tm0zu6lPlrPpzU22V87(uintptr_t arg0,uintptr_t arg1) {
   uint16_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (uint16_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I);
}
int64_t myhello_upcall_aEzr23zCPKfe1fXelr305(uintptr_t arg0,uintptr_t arg1) {
   int64_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (int64_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I);
}
void myhello_upcall_dWOanDboJh1KmRiOCPpbK4(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uint16_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uint16_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].C);
}
void myhello_upcall_ADQhs6XF4QbsWN6KmxRZA2(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uint16_t arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uint16_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].C, args[4].I);
}
void myhello_upcall_H0L1TqhiKEufSuBF7inav2(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,double arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,double arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].D);
}
uintptr_t myhello_upcall_cI2OKU5UNUJDsnfKK5byS7(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int32_t arg3) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].P, args[3].I);
}
void myhello_upcall_NfLrRofZrGfFIqokieLHF7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,int32_t arg1) = (void (*)(uintptr_t arg0,int32_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].I);
}
int8_t myhello_upcall_RQmroVTzHhJaIQXFl9bh73(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I);
}
uintptr_t myhello_upcall_ZhUhzaNNnNtGhcgK3jQ2p(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].I, args[3].P, args[4].I);
}
void myhello_upcall_ylb36BoSuhu2Hxgfjy2264(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int32_t arg4,int8_t arg5) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int32_t arg4,int8_t arg5))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].P, args[4].I, args[5].Z);
}
uintptr_t myhello_upcall_gLvGw6pnk7adUAtHTIqFG2(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I, args[3].I);
}
uintptr_t myhello_upcall_wXdCkTGvqKGdxXucvDMDn(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P);
}
uintptr_t myhello_upcall_ih0WoD1E2yxw08VLYQszy4(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].I, args[3].P);
}
uintptr_t myhello_upcall_jf37Q2ElCaEBXuF100HaE7(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I);
}
void myhello_upcall_ENSTGmF5FyL7l7dG8tSJ36(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].P, args[4].I);
}
uintptr_t myhello_upcall_KoNqjiiEQiuDKzYvBmfqA2(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4,int32_t arg5) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4,int32_t arg5))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].P, args[3].I, args[4].I, args[5].I);
}
uintptr_t myhello_upcall_OGhofjSUaJ2BZL8IdUtPF4(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,int8_t arg2) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,int8_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].Z);
}
uintptr_t myhello_upcall_5SI0TRwmKS0EpfjLnWA5l8(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uint16_t arg1) = (uintptr_t (*)(uintptr_t arg0,uint16_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].C);
}
uintptr_t myhello_upcall_8KIEOOq5HFzOxJBvzzmms7(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0) = (uintptr_t (*)(uintptr_t arg0))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P);
}
uintptr_t myhello_upcall_eQYtyNCiIOnnAkOQLrBlY3(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int8_t arg3) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int8_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].P, args[3].Z);
}
void myhello_upcall_SUaRBbPI4TN9WTN2pNfBJ6(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int32_t arg4,int32_t arg5,int32_t arg6,int32_t arg7,int32_t arg8,int8_t arg9) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int32_t arg4,int32_t arg5,int32_t arg6,int32_t arg7,int32_t arg8,int8_t arg9))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].f, args[4].I, args[5].I, args[6].I, args[7].I, args[8].I, args[9].Z);
}
void myhello_upcall_nATwijWNDNmeQdUHtHVQV6(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,int8_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4) = (void (*)(uintptr_t arg0,int8_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].Z, args[2].P, args[3].P, args[4].P);
}
void myhello_upcall_GGKHxiizNJlZqsc2e0BZ34(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I);
}
void myhello_upcall_GrqdMAo5WADB2zdfFvqPW6(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int8_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int8_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].Z);
}
void myhello_upcall_HjgmkKI1RSaa4V5vemIas2(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].P);
}
uintptr_t myhello_upcall_gZ8rq5ucxynjsZlmAxEbu4(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4,uintptr_t arg5,uintptr_t arg6,int8_t arg7) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4,uintptr_t arg5,uintptr_t arg6,int8_t arg7))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].I, args[3].P, args[4].I, args[5].P, args[6].P, args[7].Z);
}
int32_t myhello_upcall_xLfh0pQ4Zn9FkisFVa89A3(uintptr_t arg0,uintptr_t arg1) {
   int32_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3) = (int32_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I, args[3].I);
}
uintptr_t myhello_upcall_RhLfzuwC0JZAex2OaO7tL5(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].P);
}
int8_t myhello_upcall_x4gf55Jz1AtMj6dBsceBw7(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P);
}
void myhello_upcall_SdeQzO4ZvTw1ksOmCLUew5(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4,int32_t arg5,int32_t arg6) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4,int32_t arg5,int32_t arg6))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].I, args[4].P, args[5].I, args[6].I);
}
uintptr_t myhello_upcall_OreI6NwjbDwF7L9hlVwOO(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,uint16_t arg2) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,uint16_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].C);
}
uint16_t myhello_upcall_6uDZ153UAuFFuxMyyJHUn7(uintptr_t arg0,uintptr_t arg1) {
   uint16_t (*func)(uintptr_t arg0,uintptr_t arg1) = (uint16_t (*)(uintptr_t arg0,uintptr_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P);
}
uintptr_t myhello_upcall_9wChVhfqNWnbbDskm1sR76(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].P, args[3].I, args[4].I);
}
int8_t myhello_upcall_Ld9SvU4svrhpYNHWrxPCX4(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P);
}
void myhello_upcall_nm1FwXESGHKMal5Lv9qvM(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,int32_t arg4,int32_t arg5) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,int32_t arg4,int32_t arg5))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].I, args[4].I, args[5].I);
}
void myhello_upcall_FLBEHf56plJZsQaRLJ9B54(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int8_t arg2) = (void (*)(uintptr_t arg0,uintptr_t arg1,int8_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].Z);
}
void myhello_upcall_UXa64oZrGrn6zyPhFFaV0(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4,int32_t arg5) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4,int32_t arg5))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].I, args[4].P, args[5].I);
}
int8_t myhello_upcall_ZFj5I46MFlvl8sVw3vaJs(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P);
}
uintptr_t myhello_upcall_6wFNMG8WooFRkyJs5YdMF5(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,int8_t arg2) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,int8_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].B);
}
void myhello_upcall_psMber4py3FEOX8xCLN98(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int64_t arg2) = (void (*)(uintptr_t arg0,uintptr_t arg1,int64_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].J);
}
void myhello_upcall_4YbAUQ72hT6VHB9NHs69c7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int8_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int8_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].P, args[4].Z);
}
void myhello_upcall_wINsCfhllTCYpYynA9r0l4(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4,int64_t arg5) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4,int64_t arg5))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].P, args[4].P, args[5].J);
}
uintptr_t myhello_upcall_s5odBoQEG0baBSZvmYZwQ8(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,uint16_t arg2,uint16_t arg3) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,uint16_t arg2,uint16_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].C, args[3].C);
}
uintptr_t myhello_upcall_NxpQ5YtbvqOcbfmJNJxBl8(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,int32_t arg2) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].I);
}
void myhello_upcall_ZWD29W9sR3Q96cHPwjk8h4(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,int64_t arg1,int32_t arg2) = (void (*)(uintptr_t arg0,int64_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].J, args[2].I);
}
void myhello_upcall_kH6PPN83ygfntLHQVizqC(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3) = (void (*)(uintptr_t arg0,int32_t arg1,int32_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].I, args[2].I, args[3].P);
}
void myhello_upcall_y3kS1qVfG9MyWvFGfHW3Z4(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,int64_t arg1) = (void (*)(uintptr_t arg0,int64_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].J);
}
uintptr_t myhello_upcall_ezccmrAkruGgEkrhl8mpE8(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int64_t arg1,int32_t arg2) = (uintptr_t (*)(uintptr_t arg0,int64_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].J, args[2].I);
}
uintptr_t myhello_upcall_I6dkRK8TStZGxESt2WzJq4(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int64_t arg1) = (uintptr_t (*)(uintptr_t arg0,int64_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].J);
}
int64_t myhello_upcall_o2qQG8OzJbUTw3SsZqMR23(uintptr_t arg0,uintptr_t arg1) {
   int64_t (*func)(uintptr_t arg0,uintptr_t arg1) = (int64_t (*)(uintptr_t arg0,uintptr_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P);
}
void myhello_upcall_TbiobxppawChoS8YYO6J7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4,int32_t arg5,uintptr_t arg6) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4,int32_t arg5,uintptr_t arg6))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].I, args[4].I, args[5].I, args[6].P);
}
void myhello_upcall_fm0lss3LkeofuMMwa0mRD3(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4,int32_t arg5) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4,int32_t arg5))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].I, args[4].I, args[5].I);
}
void myhello_upcall_yc1DbLn7z8aAJz4OWFTUC7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,int64_t arg1,int32_t arg2,uintptr_t arg3) = (void (*)(uintptr_t arg0,int64_t arg1,int32_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].J, args[2].I, args[3].P);
}
int32_t myhello_upcall_rYd9z2PPbe1lHPQI1LRZj7(uintptr_t arg0,uintptr_t arg1) {
   int32_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2) = (int32_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P);
}
void myhello_upcall_PY1AHtP1YMQgCcBNbweW07(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4,int32_t arg5) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int32_t arg4,int32_t arg5))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].P, args[4].I, args[5].I);
}
uintptr_t myhello_upcall_3ixwtIxLzRZUDsLpWdJen2(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].I, args[4].I);
}
void myhello_upcall_LWyYqU3x72xiHwuQsavdY2(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,uintptr_t arg4,int32_t arg5) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,uintptr_t arg4,int32_t arg5))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].P, args[4].P, args[5].I);
}
int64_t myhello_upcall_WhOlXIb2zpd9wco4I7Eli3(uintptr_t arg0,uintptr_t arg1) {
   int64_t (*func)(uintptr_t arg0,int32_t arg1) = (int64_t (*)(uintptr_t arg0,int32_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I);
}
uintptr_t myhello_upcall_WHujB3wSDm2GuqwOctpLv7(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,uintptr_t arg3) = (uintptr_t (*)(uintptr_t arg0,int32_t arg1,uintptr_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].P, args[3].P);
}
int32_t myhello_upcall_14g9OHkLNmJeAU9mfGCEx7(uintptr_t arg0,uintptr_t arg1) {
   int32_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3) = (int32_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].P);
}
void myhello_upcall_11sr2zMf8hDcUmQc4E31A(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,int32_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,int32_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].J, args[3].I);
}
void myhello_upcall_Q2BVUjXGFcCUR5oy8x3nc6(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].P, args[4].P);
}
int8_t myhello_upcall_XfBho7AfVJ6RXc92u5gBN6(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].I, args[3].P);
}
void myhello_upcall_zEh95pYK9loSV15m2YAo25(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,float arg2) = (void (*)(uintptr_t arg0,uintptr_t arg1,float arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].F);
}
void myhello_upcall_Yep7WKCoQMq7TWX44UuTD5(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4,uintptr_t arg5,uintptr_t arg6,int8_t arg7,uintptr_t arg8) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4,uintptr_t arg5,uintptr_t arg6,int8_t arg7,uintptr_t arg8))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].P, args[4].P, args[5].P, args[6].P, args[7].Z, args[8].P);
}
void myhello_upcall_wsci3sC4LgjAbTUPEjLJb(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int64_t arg3,int32_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int64_t arg3,int32_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].J, args[4].I);
}
void myhello_upcall_PRvKNCn8iqyO1ws29tvvH4(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int64_t arg3,int64_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int64_t arg3,int64_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].J, args[4].J);
}
int32_t myhello_upcall_F2bTMdNJ2c555by8BWRd33(uintptr_t arg0,uintptr_t arg1) {
   int32_t (*func)(uintptr_t arg0,int64_t arg1) = (int32_t (*)(uintptr_t arg0,int64_t arg1))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].J);
}
void myhello_upcall_lOQ0tMMdVOAoOBpJdEetr6(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int8_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,int8_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].I, args[4].Z);
}
void myhello_upcall_qNLOhSn95RzX5lXyOeEFz7(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,uintptr_t arg4,uintptr_t arg5,int8_t arg6) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3,uintptr_t arg4,uintptr_t arg5,int8_t arg6))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].I, args[4].P, args[5].P, args[6].Z);
}
int8_t myhello_upcall_GRUwxlsmMVYTgwluJUVhy6(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,int8_t arg2,int32_t arg3,uintptr_t arg4,int32_t arg5,int32_t arg6) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,int8_t arg2,int32_t arg3,uintptr_t arg4,int32_t arg5,int32_t arg6))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].Z, args[3].I, args[4].P, args[5].I, args[6].I);
}
void myhello_upcall_ZPxKgPFIW6PvV8j56bZjB6(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,float arg3,float arg4,uintptr_t arg5) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,float arg3,float arg4,uintptr_t arg5))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].F, args[4].F, args[5].P);
}
uintptr_t myhello_upcall_ACjFZVKF6lEhU76iQRZYF4(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int8_t arg4) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,int8_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].P, args[3].P, args[4].Z);
}
int32_t myhello_upcall_aGQz3o2R3jbguIwq2tb0S6(uintptr_t arg0,uintptr_t arg1) {
   int32_t (*func)(uintptr_t arg0,int32_t arg1,uintptr_t arg2) = (int32_t (*)(uintptr_t arg0,int32_t arg1,uintptr_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].I, args[2].P);
}
void myhello_upcall_diyWWwdzHBj594YNWILF85(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,int64_t arg3,uintptr_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,int64_t arg3,uintptr_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].J, args[3].J, args[4].P);
}
int8_t myhello_upcall_PnLeTu8HxtNoUQ3U93aQG5(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,int64_t arg3) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,int64_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].J, args[3].J);
}
void myhello_upcall_PiK8NTbLRMcJKb9Oolb4d3(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,uintptr_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].J, args[3].P);
}
void myhello_upcall_db1YjOISfp2Hhc9965gF(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4,int64_t arg5,uintptr_t arg6) = (void (*)(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,uintptr_t arg3,uintptr_t arg4,int64_t arg5,uintptr_t arg6))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].P, args[3].P, args[4].P, args[5].J, args[6].P);
}
void myhello_upcall_h2BMU5XjiwqAqdKfHQCH9(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int16_t arg2,uintptr_t arg3) = (void (*)(uintptr_t arg0,uintptr_t arg1,int16_t arg2,uintptr_t arg3))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].S, args[3].P);
}
void myhello_upcall_RNTFqwMK8u4boMD9Rabdy8(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4) = (void (*)(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].P, args[2].I, args[3].I, args[4].f);
}
int8_t myhello_upcall_fyTphXgtNAhOA5Q2LFpih(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,uint16_t arg2) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,uint16_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].C);
}
int8_t myhello_upcall_dIY2zU01pkPn8JFt4DhAd6(uintptr_t arg0,uintptr_t arg1) {
   int8_t (*func)(uintptr_t arg0,uintptr_t arg1,uint16_t arg2) = (int8_t (*)(uintptr_t arg0,uintptr_t arg1,uint16_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].C);
}
uintptr_t myhello_upcall_ZscDmd95HpXPeNPoMGERa3(uintptr_t arg0,uintptr_t arg1) {
   uintptr_t (*func)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,int32_t arg3,uintptr_t arg4) = (uintptr_t (*)(uintptr_t arg0,uintptr_t arg1,int64_t arg2,int32_t arg3,uintptr_t arg4))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].P, args[2].J, args[3].I, args[4].P);
}
int64_t myhello_upcall_7tqbcL37gA1nG2595jGYC3(uintptr_t arg0,uintptr_t arg1) {
   int64_t (*func)(uintptr_t arg0,int64_t arg1,int64_t arg2) = (int64_t (*)(uintptr_t arg0,int64_t arg1,int64_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   return func(args[0].P, args[1].J, args[2].J);
}
void myhello_upcall_nA9IjQoo2lPsbH6FUpLBk6(uintptr_t arg0,uintptr_t arg1) {
   void (*func)(uintptr_t arg0,int32_t arg1,int32_t arg2) = (void (*)(uintptr_t arg0,int32_t arg1,int32_t arg2))arg0;
   fivmr_Value *args=(fivmr_Value*)arg1;
   func(args[0].P, args[1].I, args[2].I);
}
